name: storage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & State
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.0.3           # ← ekledik

  # HTTP & Fotoğraf seçimi
  http: ^0.13.5
  image_picker: ^0.8.7+4
  lottie: ^2.4.0

  # Küçük kalıcı veri (örn. profil yolu)
  shared_preferences: ^2.1.1

  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  firebase_storage: ^12.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/anim/login_bg.json
    - assets/anim/register.json
    - assets/anim/welcome.json
    - assets/anim/cart.json
    - assets/anim/star.json
    - assets/anim/payment.json
    - assets/anim/search.json
    - assets/anim/notification.json
