// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxzS-B7fEOuVvAQh7mfNxCXf6UbxBp7ys',
    appId: '1:371073606458:web:2ff18aa9a4188392652603',
    messagingSenderId: '371073606458',
    projectId: 'storege-9e7e7',
    authDomain: 'storege-9e7e7.firebaseapp.com',
    // Güncel Storage bucket adresi:
    storageBucket: 'storege-9e7e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75nU0j6rvcudIZOZ9pxJerPs337ODdYI',
    appId: '1:371073606458:android:caa6143c0bd402ff652603',
    messagingSenderId: '371073606458',
    projectId: 'storege-9e7e7',
    // Güncel Storage bucket adresi:
    storageBucket: 'storege-9e7e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbNZFd8PiYEkJ89goRyzvv2mVyhpBVo4s',
    appId: '1:371073606458:ios:4fa47084daeb3992652603',
    messagingSenderId: '371073606458',
    projectId: 'storege-9e7e7',
    iosBundleId: 'com.example.storage',
    // Güncel Storage bucket adresi:
    storageBucket: 'storege-9e7e7.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbNZFd8PiYEkJ89goRyzvv2mVyhpBVo4s',
    appId: '1:371073606458:ios:4fa47084daeb3992652603',
    messagingSenderId: '371073606458',
    projectId: 'storege-9e7e7',
    iosBundleId: 'com.example.storage',
    // Güncel Storage bucket adresi:
    storageBucket: 'storege-9e7e7.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxzS-B7fEOuVvAQh7mfNxCXf6UbxBp7ys',
    appId: '1:371073606458:web:3a981293387c3788652603',
    messagingSenderId: '371073606458',
    projectId: 'storege-9e7e7',
    authDomain: 'storege-9e7e7.firebaseapp.com',
    // Güncel Storage bucket adresi:
    storageBucket: 'storege-9e7e7.appspot.com',
  );
}
